seccion:
    path:     /
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:index" }

seccion_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:show" }

seccion_new:
    path:     /new
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:new" }

seccion_create:
    path:     /create
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:create" }
    requirements: { _method: post }

seccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:edit" }

seccion_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:update" }
    requirements: { _method: post|put }

seccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeDistribucionBundle:Seccion:delete" }
    requirements: { _method: post|delete }
