Cliente:
    type: entity
    table: Cliente
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombreEncargo:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: nombre_encargo
        nombreEmpresa:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: nombre_empresa
        telefono:
            type: string
            length: 15
            fixed: false
            nullable: false
        dui:
            type: string
            length: 15
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
