parameters:
#    acme_distribucion.example.class: Acme\DistribucionBundle\Example

services:
#    acme_distribucion.example:
#        class: %acme_distribucion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
